#!/usr/bin/env python3
"""Reduce inbox events → current item states. Output INBOX.md or JSON."""
import json
import os
import sys
from datetime import datetime, timezone

INBOX_DIR = "plans/_dashboard/inbox"
INBOX_FILE = os.path.join(INBOX_DIR, "inbox.jsonl")
INBOX_MD = os.path.join(INBOX_DIR, "INBOX.md")


def reduce() -> dict[str, dict]:
    """Fold events. Latest event per id wins."""
    items: dict[str, dict] = {}
    if not os.path.exists(INBOX_FILE):
        return items

    with open(INBOX_FILE) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                event = json.loads(line)
            except json.JSONDecodeError:
                continue

            eid = event.get("id", "")
            if event.get("event") == "resolve":
                if eid in items:
                    items[eid]["status"] = event.get("status", "resolved")
                    items[eid]["resolved"] = event.get("resolved")
                    items[eid]["resolved_by"] = event.get("resolved_by")
                    items[eid]["resolution_note"] = event.get("resolution_note")
                    items[eid]["updated"] = event.get("updated", items[eid].get("updated"))
            else:
                # Full item upsert
                items[eid] = event
    return items


def render_md(items: dict[str, dict]):
    open_items = [i for i in items.values() if i.get("status") == "open"]
    resolved_items = [i for i in items.values() if i.get("status") in ("resolved", "dismissed")]

    # Sort: severity desc, then age asc
    sev_order = {"critical": 0, "high": 1, "moderate": 2, "low": 3, "trivial": 4}
    open_items.sort(key=lambda i: (sev_order.get(i.get("severity", "low"), 9), i.get("created", "")))
    resolved_items.sort(key=lambda i: i.get("resolved", ""), reverse=True)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "<!-- GENERATED by scripts/inbox-render.py — do not edit by hand -->",
        "# Inbox",
        "",
        f"Last rendered: {now}",
        "",
    ]

    # Split open into advisories + issues
    advisories = [i for i in open_items if i.get("kind") == "advisory"]
    issues = [i for i in open_items if i.get("kind") != "advisory"]

    auto_clearable = sum(1 for i in issues if i.get("auto_clearable"))

    if advisories:
        lines.append(f"## Advisories · {len(advisories)} awaiting your green-light")
        lines.append("")
        lines.append("| ID | Awaits | Source |")
        lines.append("|----|--------|--------|")
        for item in advisories[:20]:
            sid = item["id"][:10]
            awaits = item.get("awaits", "") or ""
            source = item.get("source", "")
            lines.append(f"| `{sid}` | {awaits} | {source} |")
            opts = item.get("options", [])
            for j, opt in enumerate(opts[:5], 1):
                lines.append(f"| | [{j}] {opt.get('label', '')} | `{opt.get('command', '')}` |")
        lines.append("")

    if issues:
        lines.append(f"## Issues · {len(issues)} open ({auto_clearable} auto-clearable)")
        lines.append("")
        lines.append("| ID | Title | Source | Severity | Action |")
        lines.append("|----|-------|--------|----------|--------|")
        for item in issues[:30]:
            sid = item["id"][:10]
            title = (item.get("title", "") or "")[:60]
            source = item.get("source", "")
            severity = item.get("severity", "")
            sev_icon = {"critical": "🔴", "high": "🟠", "moderate": "🟡", "low": "🟢", "trivial": "⚪"}.get(severity, "")
            action = "auto" if item.get("auto_clearable") else "user"
            lines.append(f"| `{sid}` | {title} | {source} | {sev_icon} {severity} | {action} |")
        lines.append("")

    if resolved_items:
        lines.append(f"## Recently Resolved · {len(resolved_items)} items")
        lines.append("")
        for item in resolved_items[:10]:
            sid = item["id"][:10]
            title = (item.get("title", "") or "")[:80]
            lines.append(f"- `{sid}` {title}")

    os.makedirs(INBOX_DIR, exist_ok=True)
    with open(INBOX_MD, "w") as f:
        f.write("\n".join(lines) + "\n")


def render_json(items: dict[str, dict], status_filter="open", source_filter=None,
                severity_filter=None, limit=None):
    result = list(items.values())
    if status_filter != "all":
        result = [i for i in result if i.get("status") == status_filter]
    if source_filter:
        result = [i for i in result if i.get("source") == source_filter]
    if severity_filter:
        result = [i for i in result if i.get("severity") == severity_filter]
    if limit:
        result = result[:int(limit)]
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    items = reduce()
    if "--json" in sys.argv:
        kwargs = {}
        for i, arg in enumerate(sys.argv):
            if arg == "--status" and i + 1 < len(sys.argv):
                kwargs["status_filter"] = sys.argv[i + 1]
            elif arg == "--source" and i + 1 < len(sys.argv):
                kwargs["source_filter"] = sys.argv[i + 1]
            elif arg == "--severity" and i + 1 < len(sys.argv):
                kwargs["severity_filter"] = sys.argv[i + 1]
            elif arg == "--limit" and i + 1 < len(sys.argv):
                kwargs["limit"] = sys.argv[i + 1]
        render_json(items, **kwargs)
    else:
        render_md(items)
