#!/usr/bin/env python3
"""Generate budget-safe native Codex skills for canonical meta-dev commands."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


PLUGIN_ROOT = Path(__file__).resolve().parents[1]
COMMANDS_ROOT = PLUGIN_ROOT / "commands"
SKILLS_ROOT = PLUGIN_ROOT / "skills"
GENERATED_MARKER = "<!-- generated by scripts/sync-codex-command-skills.py -->"
PRESERVED_SKILLS = {
    "command-router",
    "diagnose",
    "harden",
    "ops",
    "plan",
    "review",
    "runbook",
}
REDIRECT_RE = re.compile(r"Execute /[a-z0-9-]+ \$ARGUMENTS")


def markdown_body(text: str) -> str:
    if not text.startswith("---\n"):
        return text.strip()
    parts = text.split("---", 2)
    if len(parts) != 3:
        return text.strip()
    return parts[2].strip()


def canonical_commands() -> list[Path]:
    commands = []
    for path in sorted(COMMANDS_ROOT.glob("*.md")):
        if REDIRECT_RE.fullmatch(markdown_body(path.read_text(encoding="utf-8"))):
            continue
        commands.append(path)
    return commands


def render(command: Path) -> str:
    name = command.stem
    return f"""---
name: {name}
description: "Run {name} in Codex. Trigger: {name}."
---

# {name}

{GENERATED_MARKER}

Read `../../references/workflows/command-adapter.md` and
`../../commands/{command.name}` completely, then follow both with the user's
remaining request as the command arguments.
"""


def generated_paths() -> dict[Path, str]:
    return {
        SKILLS_ROOT / command.stem / "SKILL.md": render(command)
        for command in canonical_commands()
        if command.stem not in PRESERVED_SKILLS
    }


def check() -> int:
    failures = []
    expected = generated_paths()
    for path, content in expected.items():
        if not path.is_file():
            failures.append(f"missing: {path.relative_to(PLUGIN_ROOT)}")
        elif path.read_text(encoding="utf-8") != content:
            failures.append(f"drifted: {path.relative_to(PLUGIN_ROOT)}")

    for path in SKILLS_ROOT.glob("*/SKILL.md"):
        text = path.read_text(encoding="utf-8")
        if GENERATED_MARKER in text and path not in expected:
            failures.append(f"stale: {path.relative_to(PLUGIN_ROOT)}")

    if failures:
        print("\n".join(failures))
        return 1
    print(
        "PASS: "
        f"{len(canonical_commands())} canonical commands, "
        f"{len(expected)} generated command skills"
    )
    return 0


def write() -> int:
    for path, content in generated_paths().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return check()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--write",
        action="store_true",
        help="write generated command skills; default is a drift check",
    )
    args = parser.parse_args()
    return write() if args.write else check()


if __name__ == "__main__":
    raise SystemExit(main())
